% Options for packages loaded elsewhere
% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  a4paper,
]{article}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother





\setlength{\emergencystretch}{3em} % prevent overfull lines

\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}



 


\usepackage{fontspec}
\usepackage{multirow}
\usepackage{multicol}
\usepackage{colortbl}
\usepackage{hhline}
\newlength\Oldarrayrulewidth
\newlength\Oldtabcolsep
\usepackage{longtable}
\usepackage{array}
\usepackage{hyperref}
\usepackage{float}
\usepackage{wrapfig}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Assignment 4:},
  pdfauthor={Magnus Eidesmo og Harald Vika},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Assignment 4:}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Eu statistikk.}
\author{Magnus Eidesmo og Harald Vika}
\date{Wednesday 14 Jan, 2026}
\begin{document}
\maketitle


\subsection{Toc. eurostat}\label{toc.-eurostat}

\subsection{GDP Nuts 3}\label{gdp-nuts-3}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{|p{3.50in}|p{1.50in}}



\ascline{1.5pt}{666666}{1-2}

\multicolumn{1}{>{\raggedright}m{\dimexpr 3.5in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{title}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.5in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{code}}}} \\

\ascline{1.5pt}{666666}{1-2}\endfirsthead 

\ascline{1.5pt}{666666}{1-2}

\multicolumn{1}{>{\raggedright}m{\dimexpr 3.5in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{title}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.5in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{code}}}} \\

\ascline{1.5pt}{666666}{1-2}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 3.5in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Average\ annual\ population\ to\ calculate\ regional\ GDP\ data\ (thousand\ persons)\ by\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.5in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{nama\_10r\_3popgdp}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 3.5in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Gross\ domestic\ product\ (GDP)\ at\ current\ market\ prices\ by\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.5in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{nama\_10r\_3gdp}}}} \\

\ascline{1.5pt}{666666}{1-2}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{|p{1.00in}|p{2.00in}|p{2.00in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{concept}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{code}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{name}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{concept}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{code}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{name}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{freq}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{A}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Annual}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{unit}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{MIO\_EUR}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Million\ euro}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{unit}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{EUR\_HAB}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Euro\ per\ inhabitant}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{unit}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{EUR\_HAB\_EU27\_2020}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Euro\ per\ inhabitant\ in\ percentage\ of\ the\ EU27\ (from\ 2020)\ average}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{unit}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{MIO\_NAC}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Million\ units\ of\ national\ currency}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{unit}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{MIO\_PPS\_EU27\_2020}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Million\ purchasing\ power\ standards\ (PPS,\ EU27\ from\ 2020)}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{unit}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{PPS\_EU27\_2020\_HAB}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Purchasing\ power\ standard\ (PPS,\ EU27\ from\ 2020),\ per\ inhabitant}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{unit}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{PPS\_HAB\_EU27\_2020}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Purchasing\ power\ standard\ (PPS,\ EU27\ from\ 2020),\ per\ inhabitant\ in\ percentage\ of\ the\ EU27\ (from\ 2020)\ average}}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{|p{1.00in}|p{2.00in}|p{2.00in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{concept}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{code}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{name}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{concept}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{code}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{name}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{geo}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{EU27\_2020}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{European\ Union\ -\ 27\ countries\ (from\ 2020)}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{geo}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{BE}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Belgium}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{geo}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{BE1}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Région\ de\ Bruxelles-Capitale/Brussels\ Hoofdstedelijk\ Gewest}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{geo}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{BE10}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Région\ de\ Bruxelles-Capitale/Brussels\ Hoofdstedelijk\ Gewest}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{geo}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{BE100}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Arr.\ de\ Bruxelles-Capitale/Arr.\ Brussel-Hoofdstad}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{geo}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{BE2}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Vlaams\ Gewest}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{geo}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{BE21}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Prov.\ Antwerpen}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{geo}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{BE211}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Arr.\ Antwerpen}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{geo}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{BE212}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Arr.\ Mechelen}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{geo}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{BE213}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 2in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Arr.\ Turnhout}}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\begin{verbatim}
[1] 30058     3
\end{verbatim}

\begin{verbatim}
# A tibble: 30,058 x 3
   geo   time     gdp_n3
   <chr> <chr>     <dbl>
 1 AL011 2008  551130000
 2 AL011 2009  582160000
 3 AL011 2010  664070000
 4 AL011 2011  631170000
 5 AL011 2012  717600000
 6 AL011 2013  696860000
 7 AL011 2014  735600000
 8 AL011 2015  788630000
 9 AL011 2016  801980000
10 AL011 2017  800660000
# i 30,048 more rows
\end{verbatim}

\begin{verbatim}
# A tibble: 21 x 3
   geo   time        gdp_n3
   <chr> <chr>        <dbl>
 1 IE053 2000   15837300000
 2 IE053 2001   17506250000
 3 IE053 2002   19395440000
 4 IE053 2003   19687190000
 5 IE053 2004   21000450000
 6 IE053 2005   21776750000
 7 IE053 2006   24081640000
 8 IE053 2007   26086890000
 9 IE053 2008   22705550000
10 IE053 2009   24012370000
11 IE053 2010   24085200000
12 IE053 2011   26235110000
13 IE053 2012   24346250000
14 IE053 2013   23345250000
15 IE053 2014   25127580000
16 IE053 2018   73687140000
17 IE053 2019   71965850000
18 IE053 2020   75581570000
19 IE053 2021   99064470000
20 IE053 2022  122163400000
21 IE053 2023  103989840000
\end{verbatim}

\begin{verbatim}
# A tibble: 24 x 3
   geo   time        gdp_n3
   <chr> <chr>        <dbl>
 1 IE053 2000   15837300000
 2 IE053 2001   17506250000
 3 IE053 2002   19395440000
 4 IE053 2003   19687190000
 5 IE053 2004   21000450000
 6 IE053 2005   21776750000
 7 IE053 2006   24081640000
 8 IE053 2007   26086890000
 9 IE053 2008   22705550000
10 IE053 2009   24012370000
11 IE053 2010   24085200000
12 IE053 2011   26235110000
13 IE053 2012   24346250000
14 IE053 2013   23345250000
15 IE053 2014   25127580000
16 IE053 2015   37267470000
17 IE053 2016   49407360000
18 IE053 2017   61547250000
19 IE053 2018   73687140000
20 IE053 2019   71965850000
21 IE053 2020   75581570000
22 IE053 2021   99064470000
23 IE053 2022  122163400000
24 IE053 2023  103989840000
\end{verbatim}

\section{Population
demo\_r\_pjanaggr3}\label{population-demo_r_pjanaggr3}

\subsection{oppgave 1}\label{oppgave-1}

Søker i toc\_txt for tabeller

\subsection{oppgave 2}\label{oppgave-2}

\#\#\#(i)

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{|p{8.34in}|p{1.65in}}



\ascline{1.5pt}{666666}{1-2}

\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{title}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{code}}}} \\

\ascline{1.5pt}{666666}{1-2}\endfirsthead 

\ascline{1.5pt}{666666}{1-2}

\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{title}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{code}}}} \\

\ascline{1.5pt}{666666}{1-2}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ density\ by\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{demo\_r\_d3dens}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ on\ 1\ January\ by\ age\ group,\ sex\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{demo\_r\_pjangrp3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ on\ 1\ January\ by\ broad\ age\ group,\ sex\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{demo\_r\_pjanaggr3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ structure\ indicators\ by\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{demo\_r\_pjanind3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ change\ -\ Demographic\ balance\ and\ crude\ rates\ at\ regional\ level\ (NUTS\ 3) }}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{demo\_r\_gind3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ single\ year\ of\ age\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_11ag\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ marital\ status\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_11ms\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ family\ status\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_11fs\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ sex,\ citizenship\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_01rsctz}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ sex,\ age\ group,\ current\ activity\ status\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_01rapop}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Total\ and\ active\ population\ by\ sex,\ age,\ employment\ status,\ residence\ one\ year\ prior\ to\ the\ census\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_01ramigr}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ sex,\ age\ group,\ educational\ attainment\ level,\ current\ activity\ status\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_01rews}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ sex,\ age\ group,\ household\ status\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_01rhtype}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ sex,\ age\ group,\ size\ of\ household\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_01rhsize}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Average\ annual\ population\ to\ calculate\ regional\ GDP\ data\ (thousand\ persons)\ by\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{nama\_10r\_3popgdp}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ country\ of\ citizenship,\ age\ groups\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21ctz\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ country\ of\ citizenship,\ age\ groups,\ family\ status\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21ctzf\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ country\ of\ citizenship,\ age\ groups,\ type\ of\ housing\ arrangements\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21ctzha\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ country\ of\ birth,\ age\ groups\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21cob\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ country\ of\ birth,\ age\ groups,\ household\ status\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21cobhs\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ country\ of\ birth,\ age\ groups,\ type\ of\ housing\ arrangements\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21cobha\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ marital\ status,\ broad\ age\ groups\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21m\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ family\ status,\ broad\ age\ groups\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21f\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ size\ of\ the\ locality,\ age\ groups\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21l\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ size\ of\ the\ locality,\ housing\ arrangements\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21lha\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ year\ of\ arrival\ in\ the\ country\ since\ 2010,\ age\ groups,\ groups\ of\ country\ of\ birth\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21argc\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ by\ year\ of\ arrival\ in\ the\ country,\ age\ groups,\ family\ status\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21arf\_r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ with\ Ukrainian\ citizenship\ by\ 5-year\ age\ group\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21ua\_a5r3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ with\ Ukrainian\ citizenship\ by\ age\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21ua\_ar3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ with\ Ukrainian\ citizenship\ by\ 5-year\ age\ group,\ marital\ status\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{cens\_21ua\_msr3}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 8.34in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{Population\ on\ 1st\ January\ by\ age,\ sex,\ type\ of\ projection\ and\ NUTS\ 3\ region}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 1.65in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{6}\selectfont{\global\setmainfont{Helvetica}{proj\_19rp3}}}} \\

\ascline{1.5pt}{666666}{1-2}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\begin{verbatim}
               code
             <char>
1: nama_10r_3popgdp
\end{verbatim}

Finner at koden er demo\_r\_pjanaggr3 for tabellen med forklarende tekst
«Average annual population to calculate regional GDP data (thousand
persons) by NUTS 3 regions»

\#\#\#(ii)

Last ned Data Structure Definition (DSD) for denne tabellen.

\subsubsection{(iii) (iv) og (v)}\label{iii-iv-og-v}

Tre av oppgavene i en, laster ned dataen og gi den navnet pop, plukker
ut årene fra 2000 til 2023 og den totale befolkningen, begrenser
datasettet til NUTS3 regioner og konverterer settet til en tibble.

\begin{verbatim}
[1] 30038     3
\end{verbatim}

\subsection{Oppgave 3}\label{oppgave-3}

Slå sammen GDP-data (gdp) og befolkingsdata (pop)

Kontrollerer:

\begin{verbatim}
[1] 30061     4
\end{verbatim}

\begin{verbatim}
# A tibble: 6 x 4
  geo   time     gdp_n3 pop_n3
  <chr> <chr>     <dbl>  <dbl>
1 AL011 2008  551130000 155390
2 AL011 2009  582160000 150430
3 AL011 2010  664070000 146140
4 AL011 2011  631170000 142580
5 AL011 2012  717600000 139340
6 AL011 2013  696860000 136020
\end{verbatim}

Gjør følgende tilpasning av gdp\_pop:

Regner ut gdp per capita og gir den et nytt navn:

Kontrollerer:

\begin{verbatim}
[1] 27584     5
\end{verbatim}

Sjekker om vi mangler data for enkelte år for noen soner:

\begin{verbatim}
[1] 0 5
\end{verbatim}

Var ikke noe mer NA-verdier igjen i gdp\_pc\_n3 Kvitter oss med andre
objekter for å rydde litt ettersom vi bare skal bruke eu\_data videre:

\subsection{Oppgave 4}\label{oppgave-4}

Endrer ny navn på geo til n3 og legger til variablene n2, n1 og nc fra
variabelen n3.

\subsection{Oppgave 5}\label{oppgave-5}

Undersøk om vi har noen NUTS 3 soner med pop\_n3 lik 0. Hvis det er noen
så endre disse til NA. Undersøker:

\begin{verbatim}
# A tibble: 0 x 8
# i 8 variables: n3 <chr>, time <chr>, gdp_n3 <dbl>, pop_n3 <dbl>,
#   gdp_pc_n3 <dbl>, n2 <chr>, n1 <chr>, nc <chr>
\end{verbatim}

Fant ingen rader med 0 og vi går videre, trenger ikke å endre noe til
NA.

\subsection{Oppgave 6}\label{oppgave-6}

Sjekker hvor mange NUTS3 soner vi har i hvert land, tar en
strukturkontroll:

\begin{verbatim}
# A tibble: 29 x 2
   nc    num_nuts3
   <chr>     <int>
 1 DE          400
 2 IT          107
 3 FR          100
 4 TR           81
 5 PL           73
 6 ES           59
 7 EL           52
 8 BE           44
 9 RO           42
10 AT           35
# i 19 more rows
\end{verbatim}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{|p{0.40in}|p{0.75in}|p{0.40in}|p{0.75in}|p{0.40in}|p{0.75in}|p{0.40in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-8}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Antall}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{nuts3}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{regioner}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Antall}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{nuts3}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{regioner}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Antall}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{nuts3}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{regioner}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Antall}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{nuts3}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{regioner}}}} \\

\ascline{1.5pt}{666666}{1-8}\endfirsthead 

\ascline{1.5pt}{666666}{1-8}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Antall}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{nuts3}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{regioner}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Antall}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{nuts3}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{regioner}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Antall}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{nuts3}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{regioner}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Antall}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{nuts3}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{regioner}}}} \\

\ascline{1.5pt}{666666}{1-8}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{DE}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{400}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{RO}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{42}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{CZ}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{14}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{EE}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{5}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{IT}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{107}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{AT}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{35}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{AL}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{12}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{LV}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{5}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{FR}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{100}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{BG}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{28}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{SI}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{12}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{MT}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{2}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{TR}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{81}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{RS}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{25}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{DK}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{11}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{CY}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{1}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{PL}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{73}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{HR}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{21}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{LT}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{10}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{LU}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{1}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{ES}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{59}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{SE}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{21}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{IE}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{8}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{EL}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{52}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{HU}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{20}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{MK}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{8}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{BE}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{44}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{FI}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{19}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{SK}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{8}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} \\

\ascline{1.5pt}{666666}{1-8}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\subsection{Oppgave 7}\label{oppgave-7}

Sjekker summary for gdp\_pc\_n3 for å se om hva som er har den største
og minste verdien og om det er noen NA:

\begin{verbatim}
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   2214   14994   21144   22782   27952  180416 
\end{verbatim}

Minste verdien er 2 214, mens max er på 180 416. Får ingen NA.

\subsection{Oppgave 8}\label{oppgave-8}

Bruk case\_when() for å legge til variabelen nc\_name før vi går videre.
Østerrike for AT, Belgia for BE etc..

Kontrollerer:

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{|p{0.60in}|p{0.30in}|p{0.60in}|p{0.30in}|p{0.75in}|p{0.30in}|p{0.60in}|p{0.30in}}



\ascline{1.5pt}{666666}{1-8}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{kode}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{kode}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{kode}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{kode}}}} \\

\ascline{1.5pt}{666666}{1-8}\endfirsthead 

\ascline{1.5pt}{666666}{1-8}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{kode}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{kode}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{kode}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{kode}}}} \\

\ascline{1.5pt}{666666}{1-8}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Albania}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{AL}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Estland}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{EE}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Italia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{IT}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Serbia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{RS}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Østerrike}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{AT}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Hellas}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{EL}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Litauen}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{LT}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Sverige}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{SE}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Belgia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{BE}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Spania}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{ES}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Luxemburg}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{LU}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Slovenia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{SI}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Bulgaria}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{BG}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Finland}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{FI}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Latvia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{LV}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Slovakia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{SK}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Kypros}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{CY}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Frankrike}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{FR}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Nord-Makedonia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{MK}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Tyrkia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{TR}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Tjekkia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{CZ}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Kroatia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{HR}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Malta}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{MT}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Tyskland}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{DE}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Ungarn}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{HU}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Polen}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{PL}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Danmark}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{DK}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Irland}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{IE}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Romania}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{RO}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} \\

\ascline{1.5pt}{666666}{1-8}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\section{Beregning av Gini på NUTS2, NUTS1 og NUTSc
nivå}\label{beregning-av-gini-puxe5-nuts2-nuts1-og-nutsc-nivuxe5}

Vi skal nå beregne Gini for hvert år på NUTS2, NUTS1, NUTSc og EU nivå.
Vi vil beregne Gini utfra gdp\_pc\_n3 og pop\_n3 i NUTS3 for alle
aggregeringsnivåene. Gini-koeffisient er tradisjonelt et mål på
inntektsforskjeller. Her benytter vi målet for å undersøke hvor jevnt
verdiskapningen er fordelt mellom regioner. En Gini-koeffisient nær null
vil altså her bety at verdiskapingen er jevnt fordelt mellom regionene i
et land. En Gini-koeffisient nær 1 vil det derimot bety at det meste av
verdiskapingen i et land er sentralisert til en spesifikk NUTS3 region.

\subsection{Gini- koeffisient for
NUTS2}\label{gini--koeffisient-for-nuts2}

\subsection{Oppgave 9}\label{oppgave-9}

Beregner Gini-koeffisienter på NUTS2 nivå:

Kontrollerer:

\begin{verbatim}
    gini_n2          num_reg_n2         pop_n2             gdp_n2         
 Min.   :0.00038   Min.   : 1.000   Min.   :   25740   Min.   :6.814e+08  
 1st Qu.:0.06753   1st Qu.: 2.000   1st Qu.:  992732   1st Qu.:1.595e+10  
 Median :0.10893   Median : 4.000   Median : 1529210   Median :3.030e+10  
 Mean   :0.12316   Mean   : 4.819   Mean   : 1947314   Mean   :4.679e+10  
 3rd Qu.:0.16290   3rd Qu.: 6.000   3rd Qu.: 2361818   3rd Qu.:5.388e+10  
 Max.   :0.47793   Max.   :23.000   Max.   :15874440   Max.   :7.083e+11  
 NA's   :856                                                              
   gdp_pc_n2    
 Min.   : 3157  
 1st Qu.:15317  
 Median :21839  
 Mean   :23011  
 3rd Qu.:28793  
 Max.   :96746  
                
\end{verbatim}

Får de samme tallene som kontrollen i oppgaven. Vi ser at vi har et
spenn i Gini-koeffisienten på NUTS2 nivå fra 0.0004 til 0.4779. Vi har
også 856 NAs. Vi ser også at antall NUTS3 i NUTS2 regioner spenner fra 1
til 23.

\subsection{Oppgave 10}\label{oppgave-10}

Finner observasjoner med Gini \textless{} 0.001

\begin{verbatim}
# A tibble: 4 x 10
  n2    time  n1    nc    nc_name   gini_n2  pop_n2  gdp_n2 gdp_pc_n2 num_reg_n2
  <chr> <chr> <chr> <chr> <chr>       <dbl>   <dbl>   <dbl>     <dbl>      <int>
1 DK02  2019  DK0   DK    Danmark  0.000977  837050 2.32e10    27678.          2
2 ITF5  2006  ITF   IT    Italia   0.000545  588300 1.11e10    18935.          2
3 PL43  2011  PL4   PL    Polen    0.000854 1010350 1.43e10    14181.          2
4 SK03  2004  SK0   SK    Slovakia 0.000379 1352530 1.35e10     9967.          2
\end{verbatim}

Får opp 4 obervasjoner Se så på kjennetegnet ved disse regionene:

\begin{verbatim}
# A tibble: 4 x 7
  nc_name  n2    time   gini_n2 num_reg_n2  pop_n2 gdp_pc_n2
  <chr>    <chr> <chr>    <dbl>      <int>   <dbl>     <dbl>
1 Danmark  DK02  2019  0.000977          2  837050    27678.
2 Italia   ITF5  2006  0.000545          2  588300    18935.
3 Polen    PL43  2011  0.000854          2 1010350    14181.
4 Slovakia SK03  2004  0.000379          2 1352530     9967.
\end{verbatim}

Det som blir observert her er at de fleste har få NUTS3-regioner i sine
NUTS2, noe som gjør at alle NUTS3 regionene er omtrent lik gdp\_pc\_n3
eller om det bare er en region. Derfor får disse observasjonene en
ekstremt lav Gini.

\subsection{Oppgave 11}\label{oppgave-11}

Beregn Gini-koeffsienter på NUTS1-nivå, der gdp\_pc\_n2 eller pop\_n2
ikke skal brukes som grunnlag:

Kontrollerer:

\begin{verbatim}
    gini_n1          num_reg_n1        gdp_n1              pop_n1        
 Min.   :0.01601   Min.   : 1.00   Min.   :6.814e+08   Min.   :   25740  
 1st Qu.:0.09123   1st Qu.: 6.00   1st Qu.:4.256e+10   1st Qu.: 2689490  
 Median :0.13959   Median : 9.00   Median :7.888e+10   Median : 3934280  
 Mean   :0.15364   Mean   :12.22   Mean   :1.187e+11   Mean   : 4938602  
 3rd Qu.:0.18790   3rd Qu.:14.00   3rd Qu.:1.411e+11   3rd Qu.: 5992840  
 Max.   :0.42934   Max.   :96.00   Max.   :7.287e+11   Max.   :18031860  
 NA's   :177                                                             
   gdp_pc_n1    
 Min.   : 3802  
 1st Qu.:15750  
 Median :22295  
 Mean   :23523  
 3rd Qu.:29340  
 Max.   :90512  
                
\end{verbatim}

Får de samme tallene som oppgaven. Vi ser at vi har et spenn i
Gini-koeffisienten på NUTS1 nivå fra 0.016 til 0.429. Antall NAs er nå
177. Vi ser at antall NUTS3 i NUTS1 regioner spenner helt fra 1 til 96.

\subsection{Oppgave 12}\label{oppgave-12}

Beregn Gini-koeffisienter på nasjonsnivå Måler hvor jevnt
verdiskapningen er fordelt mellom regioner innen samme land:

Kontrollerer

\begin{verbatim}
    gini_nc         num_reg_nc         gdp_nc              pop_nc        
 Min.   :0.1111   Min.   :  1.00   Min.   :5.892e+09   Min.   :  386200  
 1st Qu.:0.1742   1st Qu.:  8.00   1st Qu.:4.350e+10   1st Qu.: 2810745  
 Median :0.2094   Median : 20.00   Median :1.516e+11   Median : 6984230  
 Mean   :0.2149   Mean   : 42.37   Mean   :4.114e+11   Mean   :17122006  
 3rd Qu.:0.2553   3rd Qu.: 44.00   3rd Qu.:3.447e+11   3rd Qu.:11352985  
 Max.   :0.3991   Max.   :400.00   Max.   :3.550e+12   Max.   :84979990  
 NA's   :46                                                              
   gdp_pc_nc    
 Min.   : 4854  
 1st Qu.:15103  
 Median :22224  
 Mean   :23761  
 3rd Qu.:29362  
 Max.   :90512  
                
\end{verbatim}

Får samme som oppgaven. På landsnivå varierer Gini fra 0,1111 til
0,3991. Antall NUTS3 regioner per land varierer fra 1 til 400.

\section{``Nestete'' datastrukturer}\label{nestete-datastrukturer}

Vi vil nå «neste» de ulike gini\_NUTS* datasettene og sette dem sammen
til et nestet datasett eu\_data\_nestet som innholder alle dataene
ovenfor i en fint ordnet struktur.

\subsection{Oppgave 13}\label{oppgave-13}

``neste'' dataene på NUTS3 nivå

\begin{verbatim}
# A tibble: 29 x 3
   nc    nc_name   NUTS3_data          
   <chr> <chr>     <list>              
 1 AL    Albania   <tibble [168 x 7]>  
 2 AT    Østerrike <tibble [805 x 7]>  
 3 BE    Belgia    <tibble [880 x 7]>  
 4 BG    Bulgaria  <tibble [644 x 7]>  
 5 CY    Kypros    <tibble [23 x 7]>   
 6 CZ    Tjekkia   <tibble [322 x 7]>  
 7 DE    Tyskland  <tibble [9,200 x 7]>
 8 DK    Danmark   <tibble [253 x 7]>  
 9 EE    Estland   <tibble [115 x 7]>  
10 EL    Hellas    <tibble [1,196 x 7]>
# i 19 more rows
\end{verbatim}

\subsection{Oppgave 14}\label{oppgave-14}

«Nest» dataene på NUTS2 nivå. Legg resultatet gini\_NUTS2\_nest. Bruk
.key = ``NUTS2\_data''.

\subsection{Oppgave 15}\label{oppgave-15}

«Nest» dataene på NUTS1 nivå. Legg resultatet gini\_NUTS1\_nest.

\subsection{Oppgave 16}\label{oppgave-16}

«Nest» dataene på nasjonsnivå. Legg resultatet i gini\_NUTSc\_nest.

\subsection{Oppgave 17}\label{oppgave-17}

«Nest» dataene på EU nivå, dvs. Gini for samtlige NUTS3 regioner hvert
år. Legger resultatet i gini\_NUTSeu\_nest. \_nest er her litt
misvisende siden vi ikke gjør noen nesting.

\subsection{Oppgave 18}\label{oppgave-18}

Vis utviklingen i Gini-koeffisienten for NUTS3 regioner i EU vha. et
linjeplot.

\pandocbounded{\includegraphics[keepaspectratio]{MSB105Ass4_files/figure-pdf/unnamed-chunk-50-1.pdf}}

\subsection{Oppgave 19}\label{oppgave-19}

«The EU's Structural Funds and Cohesion Fund direct funding to NUTS
level 2 regions based on their GDP (PPS) per capita in comparison to the
EU average: less developed regions (less than 75\%), transition regions
(between 75\% and 90\% and more developed regions (over 90\%). For the
period 2014--20, EUR 351 billion will be invested in the EU's regions
with most being directed to the less developed regions.»

Basert på plottet fra foregående oppgave diskuter (veldig!) kort om
tiltaket ser ut til å virke: Plottet gir støtte til at regional ulikhet
har avtatt over tid i EU, noe som er forenlig med at kohesjonspolitikken
kan ha hatt effekt, men analysen kan ikke fastslå årsakssammenheng.

\subsection{Oppgave 20}\label{oppgave-20}

Ta gini\_n3\_nestsom utgangspunkt og bruk left\_join() til å legge til
datasettene gini\_NUTS2\_nest, gini\_NUTS1\_nest og gini\_NUTSc\_nest.

slette alle objekter utenom eu\_data og eu\_data\_nested.

\#Plots som viser utvikling \#\# Oppgave 21 Lag et linjeplot i ggplot
som viser utviklingen i Gini-koeffisient på nasjonsnivå for de 29
landene vi har med.

Får plotten:

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{MSB105Ass4_files/figure-pdf/fig-ginialle-1.pdf}}

}

\caption{\label{fig-ginialle}Utviklingen over tid for Gini-koeffisienten
for de 29 landene}

\end{figure}%

\subsection{Oppgave 22}\label{oppgave-22}

Lager en sortert tabell for Gini i år 2022 som gjør det litt lettere å
se hvilken linje som hører til hvilket land.

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{|p{1.41in}|p{1.30in}}



\ascline{1.5pt}{666666}{1-2}

\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Gini-koeffisient}}}} \\

\ascline{1.5pt}{666666}{1-2}\endfirsthead 

\ascline{1.5pt}{666666}{1-2}

\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Gini-koeffisient}}}} \\

\ascline{1.5pt}{666666}{1-2}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Irland}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.3990713}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Bulgaria}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.3172612}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Romania}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2998082}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Latvia}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2981280}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Ungarn}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2692496}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Serbia}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2637424}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Tyrkia}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2540632}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Polen}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2302756}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Malta}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2294089}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Litauen}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2259366}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Slovakia}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2222795}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Danmark}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2222566}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Estland}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2180376}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Nord-Makedonia}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2095793}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Kroatia}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2085360}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Hellas}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2077325}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Frankrike}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2062529}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Tjekkia}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2050454}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Tyskland}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2024255}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Belgia}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.1945446}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Italia}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.1907755}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Slovenia}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.1690681}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Spania}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.1340889}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Sverige}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.1263810}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Østerrike}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.1244962}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Finland}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.1111034}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Kypros}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 1.41in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{Luxemburg}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.3in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{}}}} \\

\ascline{1.5pt}{666666}{1-2}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.1}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{|p{0.60in}|p{0.40in}|p{0.60in}|p{0.40in}|p{0.75in}|p{0.40in}|p{0.60in}|p{0.40in}}



\ascline{1.5pt}{666666}{1-8}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Gini}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{koeff.}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Gini}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{koeff.}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Gini}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{koeff.}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Gini}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{koeff.}}}} \\

\ascline{1.5pt}{666666}{1-8}\endfirsthead 

\ascline{1.5pt}{666666}{1-8}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Gini}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{koeff.}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Gini}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{koeff.}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Gini}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{koeff.}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Land}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{Gini}}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{\linebreak }}}\textcolor[HTML]{000000}{\fontsize{9}{9}\selectfont{\global\setmainfont{Helvetica}{koeff.}}}} \\

\ascline{1.5pt}{666666}{1-8}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Irland}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.399}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Polen}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.230}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Kroatia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.209}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Slovenia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.169}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Bulgaria}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.317}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Malta}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.229}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Hellas}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.208}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Spania}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.134}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Romania}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.300}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Litauen}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.226}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Frankrike}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.206}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Sverige}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.126}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Latvia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.298}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Slovakia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.222}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Tjekkia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.205}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Østerrike}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.124}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Ungarn}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.269}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Danmark}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.222}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Tyskland}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.202}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Finland}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.111}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Serbia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.264}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Estland}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.218}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Belgia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.195}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Kypros}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Tyrkia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.254}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Nord-Makedonia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.210}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Italia}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{0.191}}}} & \multicolumn{1}{>{\raggedright}m{\dimexpr 0.6in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{Luxemburg}}}} & \multicolumn{1}{>{\centering}m{\dimexpr 0.4in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{9}{8}\selectfont{\global\setmainfont{Helvetica}{}}}} \\

\ascline{1.5pt}{666666}{1-8}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\subsection{Oppgave 23}\label{oppgave-23}

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{MSB105Ass4_files/figure-pdf/fig-Lavgini-1.pdf}}

}

\caption{\label{fig-Lavgini}Land med lavere regional ulikhet i 2022 enn
første år vi har data for.}

\end{figure}%

\begin{figure}[H]

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{MSB105Ass4_files/figure-pdf/fig-Hoygini-1.pdf}}

}

\caption{\label{fig-Hoygini}Land med høyere regional ulikhet i 2022 enn
første år vi har data for.}

\end{figure}%

\subsection{Oppgave 24}\label{oppgave-24}

Vis vha. et linjeplot utviklingen i gini-koeffisient for NUTS2 regionene
i Irland.

\pandocbounded{\includegraphics[keepaspectratio]{MSB105Ass4_files/figure-pdf/unnamed-chunk-60-1.pdf}}

\section{Hvordan er verdiskapningen fordelt mellom regionene i ulike
land?}\label{hvordan-er-verdiskapningen-fordelt-mellom-regionene-i-ulike-land}

Spania hadde i år 2022 en Gini-koeffisient lik 0,134 som skulle tilsi en
nokså jevn fordeling av økonomisk aktivitet mellom regionene.

\subsection{Oppgave 25}\label{oppgave-25}

Lag et line-plot som viser utviklingen i Gini-koeffisientene for NUTS2
regionene i Spania.

Kontrollerer regionene:

\begin{verbatim}
# A tibble: 11 x 1
   n2   
   <chr>
 1 ES11 
 2 ES21 
 3 ES24 
 4 ES41 
 5 ES42 
 6 ES43 
 7 ES51 
 8 ES52 
 9 ES53 
10 ES61 
11 ES70 
\end{verbatim}

Lager så linjeplottet:

\pandocbounded{\includegraphics[keepaspectratio]{MSB105Ass4_files/figure-pdf/unnamed-chunk-63-1.pdf}}

\paragraph{Oppgave 26}\label{oppgave-26}

Lag et line-plot som viser utviklingen i Gini-koeffisientene for NUTS1
regionene i Spania.

\pandocbounded{\includegraphics[keepaspectratio]{MSB105Ass4_files/figure-pdf/unnamed-chunk-64-1.pdf}}

\subsubsection{Tyskland}\label{tyskland}

\paragraph{Oppgave 27}\label{oppgave-27}

Lag et line-plot som viser utviklingen i Gini-koeffisient for NUTS2
regionene i Tyskland. Dropp gjerne farger. Det er så mange regioner at
de er vanskelig å skille.

\pandocbounded{\includegraphics[keepaspectratio]{MSB105Ass4_files/figure-pdf/unnamed-chunk-65-1.pdf}}

Vi ser at Gini-koeffisientene spenner fra ca. 0.03 til over 0.45. Det
ser altså ut til å være store forskjeller mellom NUTS2 regionene i
Tyskland. Noen NUTS2 soner ser ut til å være relativt ensartet mhp.
verdiskapning, mens andre er preget av store forskjeller mellom NUTS3
regionene. Hvor i landet er de plassert de regionene som har de største
regionale forskjellene? Figuren viser at Gini-koeffisientene for
NUTS2-regionene i Tyskland varierer fra om lag 0,03 til over 0,45. Dette
peker på betydelige forskjeller i graden av intern regional ulikhet.
Regioner med lave Gini-verdier fremstår som relativt homogene når det
gjelder verdiskaping mellom NUTS3-områder, mens regioner med høye
Gini-verdier er kjennetegnet av store interne variasjoner. De mest
markante regionale ulikhetene finnes i hovedsak i og rundt de største
økonomiske sentrene og storbyregionene, særlig i de vestlige og sørlige
delene av landet, hvor sterke kjerneområder sameksisterer med mindre
utviklede omkringliggende regioner.

\paragraph{Oppgave 28}\label{oppgave-28}

Er det samme er tilfelle når vi ser på de større regionene i Tyskland
(NUTS1)?

\pandocbounded{\includegraphics[keepaspectratio]{MSB105Ass4_files/figure-pdf/unnamed-chunk-66-1.pdf}}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{|p{0.75in}|p{0.75in}|p{0.75in}}



\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{n1}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{gini\_n1}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{num\_reg\_n1}}}} \\

\ascline{1.5pt}{666666}{1-3}\endfirsthead 

\ascline{1.5pt}{666666}{1-3}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{n1}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{gini\_n1}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{num\_reg\_n1}}}} \\

\ascline{1.5pt}{666666}{1-3}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DEB}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.2529}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{36}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DE2}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.2477}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{96}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DE7}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.2394}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{26}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DE9}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.1978}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{45}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DE5}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.1790}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{2}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DE1}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.1726}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{44}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DEA}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.1616}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{53}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DEC}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.1445}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{6}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DEF}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.1421}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{15}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DE4}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.1291}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{18}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DEG}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.1196}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{22}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DED}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.1111}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{13}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DEE}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.0953}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{14}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DE8}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{0.0947}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{8}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DE3}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{1}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{DE6}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.75in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{3}\selectfont{\global\setmainfont{Helvetica}{1}}}} \\

\ascline{1.5pt}{666666}{1-3}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\section{Frankrike}\label{frankrike}

\subsection{Oppgave 29}\label{oppgave-29}

\pandocbounded{\includegraphics[keepaspectratio]{MSB105Ass4_files/figure-pdf/unnamed-chunk-68-1.pdf}}

\paragraph{Oppgave 30}\label{oppgave-30}

Lag en tabell som viser de 6 NUTS1 sonene i Frankrike som hadde høyest
Gini-koeffisient i 2022. Hvilken sone har suverent høyest
Gini-koeffisient og hvor ligger denne i landet?

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{|p{0.62in}|p{0.78in}}



\ascline{1.5pt}{666666}{1-2}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.62in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{n1}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.78in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{gini\_n1}}}} \\

\ascline{1.5pt}{666666}{1-2}\endfirsthead 

\ascline{1.5pt}{666666}{1-2}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.62in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{n1}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.78in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{gini\_n1}}}} \\

\ascline{1.5pt}{666666}{1-2}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.62in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FR1}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.78in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.3354}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.62in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FRL}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.78in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.2018}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.62in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FRK}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.78in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.1549}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.62in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FRJ}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.78in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.1341}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.62in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FRM}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.78in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.1091}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.62in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FRF}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 0.78in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{0.1025}}}} \\

\ascline{1.5pt}{666666}{1-2}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

Tabellen viser at Île-de-France (FR1) har suverent høyest
Gini-koeffisient blant franske NUTS1-regioner i 2022. Denne regionen
ligger i nordlige deler av Frankrike og omfatter Paris og
hovedstadsområdet.

\paragraph{Oppgave 31}\label{oppgave-31}

Vi ser at for Frankrike er det en region som har klart større
forskjeller mht. vekst (verdiskapning) enn de andre. Sjekk NUTS3
regionenen i denne regionen nærmere vha. linjeplot og lag en tabell som
viser gdp\_pc\_n3 for de seks sonene.

\begin{verbatim}
# A tibble: 1 x 13
  nc    nc_name   NUTS3_data n2    time  n1    gini_n2  pop_n2  gdp_n2 gdp_pc_n2
  <chr> <chr>     <list>     <chr> <chr> <chr>   <dbl>   <dbl>   <dbl>     <dbl>
1 FR    Frankrike <tibble>   FR10  2022  FR1     0.335  1.24e7 7.08e11    57222.
# i 3 more variables: num_reg_n2 <int>, NUTS1_data <list>, NUTSc_data <list>
\end{verbatim}

Ser at det er 8 soner i denne regionen isteden for 6 som det står i
løsningsforslaget

\pandocbounded{\includegraphics[keepaspectratio]{MSB105Ass4_files/figure-pdf/unnamed-chunk-71-1.pdf}}

\global\setlength{\Oldarrayrulewidth}{\arrayrulewidth}

\global\setlength{\Oldtabcolsep}{\tabcolsep}

\setlength{\tabcolsep}{2pt}

\renewcommand*{\arraystretch}{1.5}



\providecommand{\ascline}[3]{\noalign{\global\arrayrulewidth #1}\arrayrulecolor[HTML]{#2}\cline{#3}}

\begin{longtable*}[c]{|p{0.74in}|p{1.04in}}



\ascline{1.5pt}{666666}{1-2}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.74in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{n3}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.04in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{gdp\_pc\_n3}}}} \\

\ascline{1.5pt}{666666}{1-2}\endfirsthead 

\ascline{1.5pt}{666666}{1-2}

\multicolumn{1}{>{\raggedright}m{\dimexpr 0.74in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{n3}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.04in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{gdp\_pc\_n3}}}} \\

\ascline{1.5pt}{666666}{1-2}\endhead



\multicolumn{1}{>{\raggedright}m{\dimexpr 0.74in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FR101}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.04in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{113,523}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.74in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FR105}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.04in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{101,546}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.74in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FR107}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.04in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{38,625}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.74in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FR106}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.04in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{37,017}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.74in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FR103}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.04in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{36,897}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.74in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FR104}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.04in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{36,840}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.74in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FR102}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.04in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{29,967}}}} \\





\multicolumn{1}{>{\raggedright}m{\dimexpr 0.74in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{FR108}}}} & \multicolumn{1}{>{\raggedleft}m{\dimexpr 1.04in+0\tabcolsep}}{\textcolor[HTML]{000000}{\fontsize{11}{11}\selectfont{\global\setmainfont{Helvetica}{28,995}}}} \\

\ascline{1.5pt}{666666}{1-2}



\end{longtable*}



\arrayrulecolor[HTML]{000000}

\global\setlength{\arrayrulewidth}{\Oldarrayrulewidth}

\global\setlength{\tabcolsep}{\Oldtabcolsep}

\renewcommand*{\arraystretch}{1}

\paragraph{Oppgave 32}\label{oppgave-32}

Kan vi utfra foregående plot og tabell si noe om årsaken til at FR1 har
så høy Ginikoeffisient?

Ja. Plottet og tabellen viser at FR1 (Île-de-France) har svært store
forskjeller i BNP per innbygger mellom NUTS3-regionene. Verdiskapingen
er sterkt konsentrert i Paris og de sentrale delene av regionen, mens
omkringliggende områder ligger betydelig lavere. Dette gir høy intern
ulikhet og dermed en høy Gini-koeffisient.

\subsection{Enkle modeller}\label{enkle-modeller}

\paragraph{Oppgave 33}\label{oppgave-33}

Lag datasett for endringer i gdp\_per\_capita og gini\_nuts2.

\begin{verbatim}
[1] 218
\end{verbatim}

av disse har vi kunnet beregne Gini-koeffisient for. Vi har altså 38
NUTS2 soner som bare inneholder én NUTS3 sone.

\subsection{Oppgave 34}\label{oppgave-34}

Bruk modellen diff\_gini\_nuts2 \textasciitilde{} diff\_gdp\_per\_capita
på hver av de 256 (218) NUTS2 regionene vha. en anonym funksjon som
«mappes» (vha. map()) på «list-column» NUTS2\_diff. Legg resultatet i en
variabel modell.

\subsection{Oppgave 35}\label{oppgave-35}

Hent ut koeffisientene fra de 256 (218) modellene og legg resultatet i
variabelen mod\_coeff. Gjør dette ved å «mappe» funksjonen coeff() på
list\_column modell.

\subsection{Oppgave 36}\label{oppgave-36}

Bruker glance() funksjonen fra broom pakken og «map» denne på modell
variabelen for å generere «model summary». Legg resultatet i en variabel
mod\_sum.

\subsection{Oppgave 37}\label{oppgave-37}

Hvilken NUTS1 sone har høyest 𝑅2 for vår modell og hvilken sone har
lavest?

\begin{verbatim}
# A tibble: 3 x 7
# Groups:   nc_name, n2 [3]
  nc_name  n2    NUTS2_diff        modell `(Intercept)` diff_gdp_per_capita
  <chr>    <chr> <list>            <list>         <dbl>               <dbl>
1 Polen    PL82  <tibble [92 x 6]> <lm>        -0.0364           0.00000669
2 Tyskland DED5  <tibble [69 x 6]> <lm>         0.00344         -0.00000454
3 Belgia   BE22  <tibble [60 x 6]> <lm>         0.129           -0.00000312
# i 1 more variable: mod_sum <tibble[,12]>
\end{verbatim}

\begin{verbatim}
# A tibble: 3 x 7
# Groups:   nc_name, n2 [3]
  nc_name  n2    NUTS2_diff         modell `(Intercept)` diff_gdp_per_capita
  <chr>    <chr> <list>             <list>         <dbl>               <dbl>
1 Italia   ITH3  <tibble [160 x 6]> <lm>         0.00374       -0.0000000159
2 Tyskland DE26  <tibble [276 x 6]> <lm>        -0.00903        0.0000000121
3 Tyskland DE22  <tibble [276 x 6]> <lm>        -0.0500         0.0000000523
# i 1 more variable: mod_sum <tibble[,12]>
\end{verbatim}

\subsection{Oppgave 38}\label{oppgave-38}

Hvilken NUTS1 sone har høyest koeffisient for diff\_gdp\_per\_capita?

\begin{verbatim}
# A tibble: 3 x 7
# Groups:   nc_name, n2 [3]
  nc_name  n2    NUTS2_diff         modell `(Intercept)` diff_gdp_per_capita
  <chr>    <chr> <list>             <list>         <dbl>               <dbl>
1 Bulgaria BG34  <tibble [92 x 6]>  <lm>         -0.0759           0.0000122
2 Bulgaria BG42  <tibble [115 x 6]> <lm>         -0.210            0.0000111
3 Tyrkia   TRA2  <tibble [76 x 6]>  <lm>         -0.0439           0.0000101
# i 1 more variable: mod_sum <tibble[,12]>
\end{verbatim}

NUTS2-regionen med høyest koeffisient: BG34 i Bulgaria.

\paragraph{Oppgave 39}\label{oppgave-39}

Hvor mange av de 256 (218) koeffisientene er signifikante på 5\% nivå?

\begin{verbatim}
[1] 162  18
\end{verbatim}

Ut fra tibbelen får vi et antall på 162 av de totale 218 som er
statistisk signifikante på 5 \% nivå. Dette betyr at disse regionene har
en sammenheng mellom endringer i BNP per innbygger og endringer i
regional ulikheter som kan måles med data.

\paragraph{Oppgave 40}\label{oppgave-40}

Bruk ggplot til å lage et «density plot» av variabelen
diff\_gdp\_per\_capita. Legg inn en vertikal linje for gjennomsnitt
diff\_gdp\_per\_capita. (Hint! Husk argumentet na.rm = TRUE.).
Resultatet skal bli som i plottet under.

\pandocbounded{\includegraphics[keepaspectratio]{MSB105Ass4_files/figure-pdf/unnamed-chunk-83-1.pdf}}

\paragraph{Oppgave 41}\label{oppgave-41}

Hvor mange av de 256 (218) regrersjonskoeffisientene for
diff\_gdp\_per\_capita er positive?

\begin{verbatim}
[1] 132   7
\end{verbatim}

Svaret viser et flertall av NUTS2-regionene på 132 som er om lag 61 \%,
som er sammenhengen mellom endringer i BNP per innbygger og endringer i
regional ulikhet positiv.

\paragraph{Oppgave 42}\label{oppgave-42}

\begin{verbatim}
# A tibble: 1 x 2
    mean_coef median_coef
        <dbl>       <dbl>
1 0.000000816 0.000000528
\end{verbatim}

\paragraph{Oppgave 43}\label{oppgave-43}

Utfør en enkel t-test for å teste om diff\_gdp\_per\_capita er
signifikant større enn 0. Er diff\_gdp\_per\_capita signifikant større
enn 0?

\begin{verbatim}

    One Sample t-test

data:  coef_tidy$estimate
t = 3.7658, df = 217, p-value = 0.0001069
alternative hypothesis: true mean is greater than 0
95 percent confidence interval:
 4.583272e-07          Inf
sample estimates:
  mean of x 
8.16482e-07 
\end{verbatim}

\subsection{Panel modell}\label{panel-modell}

\paragraph{Oppgave 44}\label{oppgave-44}

Bruk funksjonen plm() fra pakken plm til å utføre en panel-regresjon på
dataene. For argumentet index kan dere bruke index = c(``n3'',
``time''). Bruk samme enkle modell som ovenfor dvs. diff\_gini\_nuts2
\textasciitilde{} diff\_gdp\_per\_capita. Putt resultatet av regresjonen
i et objekt p\_mod.

\paragraph{Oppgave 45}\label{oppgave-45}

Vis summary() for p\_mod og tolk resultatet.

\begin{verbatim}
Oneway (individual) effect Within Model

Call:
plm(formula = "diff_gini_nuts2 ~ diff_gdp_per_capita", data = unnest(select(NUTS2_diff, 
    n2, NUTS2_diff), NUTS2_diff), index = c("n3", "time"))

Unbalanced Panel: n = 1186, T = 13-23, N = 26700

Residuals:
      Min.    1st Qu.     Median    3rd Qu.       Max. 
-37.335219  -0.559292  -0.035798   0.505712  27.300139 

Coefficients:
                      Estimate Std. Error t-value  Pr(>|t|)    
diff_gdp_per_capita 3.9320e-07 2.4694e-08  15.923 < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Total Sum of Squares:    78060
Residual Sum of Squares: 77291
R-Squared:      0.0098397
Adj. R-Squared: -0.036189
F-statistic: 253.536 on 1 and 25513 DF, p-value: < 2.22e-16
\end{verbatim}

Fixed effects-modellen viser en positiv og statistisk signifikant
sammenheng mellom vekst i BNP per innbygger og endring i
Gini-koeffisienten. Dette indikerer at økonomisk vekst innen regioner i
snitt er assosiert med økt regional ulikhet. Samtidig er modellens
forklaringskraft lav, noe som tilsier at andre faktorer også spiller en
viktig rolle.

\paragraph{Oppgave 46}\label{oppgave-46}

En alternativ måte å finne summary() for p\_mod er gjengitt i chunk-en
nedenfor. \textbf{Forklar hva som blir gjort her og sammenlign med
resultatet av en ordinær summary().}

\begin{verbatim}
Oneway (individual) effect Within Model

Note: Coefficient variance-covariance matrix supplied: function(x) plm::vcovHC(x, method = "white2")

Call:
plm(formula = "diff_gini_nuts2 ~ diff_gdp_per_capita", data = unnest(select(NUTS2_diff, 
    n2, NUTS2_diff), NUTS2_diff), index = c("n3", "time"))

Unbalanced Panel: n = 1186, T = 13-23, N = 26700

Residuals:
      Min.    1st Qu.     Median    3rd Qu.       Max. 
-37.335219  -0.559292  -0.035798   0.505712  27.300139 

Coefficients:
                      Estimate Std. Error t-value  Pr(>|t|)    
diff_gdp_per_capita 3.9320e-07 2.7778e-08  14.155 < 2.2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Total Sum of Squares:    78060
Residual Sum of Squares: 77291
R-Squared:      0.0098397
Adj. R-Squared: -0.036189
F-statistic: 200.369 on 1 and 1185 DF, p-value: < 2.22e-16
\end{verbatim}




\end{document}
